version: '3.9'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_storage: {}
  grafana_storage: {}
  certs:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "1000:1000"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./var/prometheus:/var/lib/prometheus
      - ./var/prometheus:/prometheus
      - ./var/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.route-prefix=/'
      - '--storage.tsdb.retention.time=745h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: ${PROMETHEUS_MEM_LIMIT}
        reservations:
          cpus: '0.25'
          memory: ${PROMETHEUS_MEM_RESERVATION}
    ports:
      - 9001:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "104"
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: ${GRAFANA_MEM_LIMIT}
        reservations:
          cpus: '0.25'
          memory: ${GRAFANA_MEM_RESERVATION}
    ports:
      - 8000:3000
    networks:
      - monitoring
    depends_on:
      - prometheus