global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitoring: 'monitoring'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'frontend-home-server'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.100:9100']

  - job_name: 'backend-home-server'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.101:9100']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['127.0.0.1:9090']

  # - job_name: 'cadvisor'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['cadvisor:9200']


  # - job_name: 'pushgateway'
  #   scrape_interval: 10s
  #   honor_labels: true
  #   static_configs:
  #     - targets: ['pushgateway:9091']

# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets: 
#       - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']